var data_game_united={
	"lists":[
		{"cl":"shendao","united_name":"Thần Đao","tw":"Đao hàm sát khí đằng u sóc <br>Tiêu táp hàn mang khấp quỷ thần","yw":"Trường đao lược thế , Hùng ưng tương tùy , Dũng giả sơ tâm vô cụ , Nhân giả tự khả vô địch. Môn phái Thần Đao là chỗ ở của Phó Hồng Tuyết cùng Diệp Khai, là môn phái đầu tiên trong giang hồ dùng đao, diệc thị bát hoang trung tối vi đặc lập độc hành 、 tiêu sái suất tính chi môn phái ...","level":4,"fs":"Trường đao lược thế , Hùng ưng tương tùy , Dũng giả sơ tâm vô cụ , Nhân giả tự khả vô địch. Môn phái Thần Đao là chỗ ở của Phó Hồng Tuyết cùng Diệp Khai, là môn phái đầu tiên trong giang hồ dùng đao, diệc thị bát hoang trung tối vi đặc lập độc hành 、 tiêu sái suất tính chi môn phái ...","wp":[["Trường Đao"],["Ưng"]],"lk":"#","gl":"#"},
		{"cl":"taibai","united_name":"Thái Bạch","tw":"Lưu tinh bạch vũ quang xuất hạp , Nhất kiếm vô ngân tuyết mạn sơn","yw":`Phong Vô Ngân nguyên bản là Ti lục Ti tham quân sự ở phủ Khai Phong, phụ trách hiệp trợ nha môn, lợi dụng khả năng phân tích cường đại để trinh thám tra án. Trong nhiều năm phá án, Phong Vô Ngân bởi vì tình cờ lấy được một quyển sách được cho là sách thuốc có tên "Phá Huyệt Luận"...`,"level":4,"fs":`Kiếm giả bách nhận chi quân dã, Thái Bạch là võ lâm đệ nhất kiếm phái. Kiếm pháp dựa vào 2 chữ "nhanh" và "ngộ" ,  kiếm ra theo ý, kiếm đi trước ý, nhiều chiêu công phá sơ hở địch, liên miên không dứt rồi lại không tìm thấy tung tích, là vì "vô ngân kiếm ý"...`,"wp":[["Kiếm"],["Vỏ kiếm"]],"lk":"#","gl":"#"},
		{"cl":"shenwei","united_name":"Thần Uy","tw":"Thần uy đảo quyển phiên không lãng, Nhất cử trùng tiêu khí thế hùng","yw":`Hậu Chu năm 954, phó đô chỉ huy sứ Hàn Thông sáng lập "Thần Uy doanh", trung thành thủ hộ hoàng thất Hậu Chu an toàn. Con trai Hàn Thông là Hàn Vi, từng mấy lần khuyên phụ thân diệt trừ trọng thần Hậu Chu Triệu Khuông Dận, nhưng Hàn Thông lại thưởng thức khí độ và tài năng của Triệu Khuông Dận...`,"level":3,"fs":"Thần Uy là môn phái xuất thân từ quân đội, cho nên vô luận là tính tình hay võ công đều mang tính chất quân đội, chú trọng thực chiến, cương mãnh bá đạo, dũng hướng lên đầu","wp":[["Thương"],["Trường cung"]],"lk":"//wuxia.qq.com/gamedata/league/shenwei.shtml","gl":"#"},
		{"cl":"tangmen","united_name":"Đường Môn","tw":"Vụ ải vân tòng phi tích lạc, Bán ảnh tương y phiến trung tình","yw":"Đường thị đất Thục, là thế gia khởi đầu từ thời Ngụy Tấn. Trong thời ngũ đại thập quốc, thiếu chủ Đường môn Đường Dĩnh cải trang lấy tên giả Lô Dĩnh, du lịch Giang Nam, rồi thị đậu Tiến sĩ, trở thành Nam Đường văn võ song Tiến sĩ, vang danh thiên hạ...","level":5,"fs":`Đường Môn là một thế gia lâu đời, sử dụng cơ quan ám khí độc bộ võ lâm, nhưng bởi vì sử dụng thuật hợp kích cùng cơ quan khôi lỗi, nên được giang hồ gọi là "nửa người nửa bóng". Những cao thủ Đường môn chân chính không cần sử dụng độc.`,"wp":[["Khôi lỗi"],["Quạt"]],"lk":"//wuxia.qq.com/gamedata/league/tangmen.shtml","gl":"#"},
		{"cl":"gaibang","united_name":"Cái Bang","tw":"Túy lai hào khí bất khả thu, Hư tác trường hồng quán ngưu đấu","yw":"Cái Bang xuất xứ có từ rất sớm nhưng phải đến thời kỳ Xuân Thu, mới chính thức làm một môn phái tồn tại trong giang hồ, còn lại là từ Đường Mạt bắt đầu phát triển. Trong khởi nghĩa Hoàng Sào, một tướng lĩnh họ Kim bất mãn với nghĩa quân bạo ngược giết hại dân chúng...","level":4,"fs":"Cái Bang lấy cận chiến làm sở trường, bao gồm rất nhiều kỹ năng khống chế liên tục","wp":[["Bao Tay"],["Hồ lô"]],"lk":"//wuxia.qq.com/gamedata/league/gaibang.shtml","gl":"//wuxia.qq.com/webplat/info/news_version3/5012/16799/16811/16812/m12360/list_1.shtml"},
		{"cl":"tianxiang","united_name":"Thiên Hương","tw":"Cạnh khoa thiên hạ song vô tuyệt, Độc lập nhân gian đệ nhất hương","yw":`Trước khi Hoa Đà bị xử tử, mang sở học tâm đắc nhất làm thành một quyển là "Thanh tâm thư". Mấy trăm năm sau, thiếu niên Tang Sài tử nhặt được quyển sách này, học tập y thuật, lần đầu tiên cứu người chính là con gái của một viên ngoại tên là Lương Tri Âm...`,"level":3,"fs":"Thiên Hương nằm trong một u cốc ở Đông Việt, giữa một biển hoa, lấy y làm võ, y võ hợp nhất, sáng tạo nên bộ võ học độc nhất. Thiên Hương là môn phái duy nhất trong giang hồ chỉ nhận nữ, thanh lệ thoát tục cũng có thanh tâm quốc sắc, chỉ có thể ái mộ mà không thể khinh nhờn","wp":[["Ô"],["Kiếm trong ô"]],"lk":"#","gl":"#"},
		{"cl":"zhenwu","united_name":"Chân Võ","tw":"Linh diệu tiềm thông thừa phong khởi, Thái cực huyền hư nhược kính thanh","yw":`Tổ sư Chân Võ Trương Mộng Bạch vốn là xuất thân thư hương môn đệ. Trong lúc đi thi, ngang qua  núi Tương Châu vô tình  gặp đạo nhân Phù Diêu Tử, được điểm hóa, Trương Mộng Bạch bỏ văn học võ, học tập được "Khu Ảnh thuật" thì lại từ võ theo văn...`,"level":4,"fs":`Võ Đang Chân Võ là chính tông đạo gia huyền môn, ý niệm truyền thừa "đại đạo bất viễn, chân ngã tồn tâm, tự nhiên thành vũ, thiên nhân hợp nhất", lấy kiếm ngự khí, khí thấu trùng tiêu, tạo nên uy danh “phi chân võ bất túc đương” `,"wp":[["Song kiếm"],["Bao kiếm"]],"lk":"//wuxia.qq.com/gamedata/league/zhenwu.shtml","gl":"#"},
		{"cl":"wudu","united_name":"Ngũ Độc","tw":"Đổng du bích lạc tâm vô ngại, Tĩnh tàng thâm uyên tích tuyệt tung","yw":`Ngũ Độc ở Vân Điền cùng chư phái Trung Nguyên đều có chỗ bất đồng, võ học lấy "ngoan", "quỷ", "độc", "nhanh" làm yếu quyết, lấy đao pháp quỷ dị lăng lệ phối hợp với thân pháp quỷ thần khó lường, có thể nói là một cái nhấc tay, lấy ngay mạng người; khói nhẹ tan hết, là thấy ngũ độc`,"level":5,"fs":"Bách quỷ tiềm hành, thận ý vô song. Môn phái Ngũ độc chuyên sử dụng đao và năng lực tiềm hành. Lai vô ảnh, khứ vô tung,  lấy thân pháp quỷ mị cùng bạo kích sát thương làm sở trường, thường thường ở trong bóng ma là có thể nắm trong tay sinh tử đối phương","wp":[["Song nhận"],["Song nhận"]],"lk":"#","gl":"#"}
	]	
};

